### PR TITLE
Enable use of Paalman-Pings absorption correction

### PR DESCRIPTION
**Pull request by jenest**
- Addresses GitLab issue [PD#65]( https://code.ornl.gov/sns-hfir-scse/diffraction/powder/powder-diffraction/-/issues/65)
- Enables options SampleOnly, SampleAndContainer, FullPaalmanPings for absorption correction

### CODE REVIEW

**Review by marshallmcdonnell — CHANGES_REQUESTED** [review]
Overall, will be a great addition.

I do have one request for change.
I think the empty `sys` file has been added accidently.
Can we remove that?

**Comment by jenest** [comment]
> Overall, will be a great addition.
> 
> I do have one request for change.
> I think the empty `sys` file has been added accidently.
> Can we remove that?

Looks like it was added by accident. It has been deleted!

**Review by marshallmcdonnell — APPROVED** [review]
LGTM!

**Comment by marshallmcdonnell** [comment]
We can ignore the code coverage.
LGTM!
Thanks for the contribution!

**Pull request merged**
