### PR TITLE
Imp PD 69

### PR DESCRIPTION
**Pull request by wdzhou**
https://code.ornl.gov/sns-hfir-scse/diffraction/powder/powder-diffraction/-/issues/69

### CODE REVIEW

**Comment by Kvieta1990** [comment]
I guess we have some issue with formatting (which fails the CI)? @wdzhou

**Comment by Kvieta1990** [comment]
@wdzhou @ckendrick Just a kind reminder that the CI is failing now complaining about link security stuff.

**Comment by ckendrick** [comment]
@Kvieta1990 thanks for the reminder, it looks like it was caused by an assert statement. I removed it and I think it should pass now.

**Comment by Kvieta1990** [comment]
Checking the codes and they look fine to me. Would you mind if I merge this PR? @marshallmcdonnell

**Comment by marshallmcdonnell** [comment]
@Kvieta1990 Yes, please! Feel free to merge if you approve! :+1:

**Comment by wdzhou** [comment]
@marshallmcdonnell and @Kvieta1990 : Thanks for merging this! 

@ckendrick : I will create another feature branch for PD #69.

**Pull request merged**
